apiVersion: v2
name: multinic-agent
description: MultiNIC 네트워크 설정 관리 에이전트
type: application
version: 0.5.0
appVersion: "0.5.0"
maintainers:
  - name: okestro
keywords:
  - multinic
  - network
  - kubernetes