# 기본 값
replicaCount: 1

image:
  repository: multinic-agent
  pullPolicy: IfNotPresent
  tag: "0.5.0"

# 데이터베이스 설정
database:
  host: "192.168.34.79"
  port: "30305"
  user: "root"
  password: "secret"
  name: "multinic"

# 에이전트 설정
agent:
  # 폴링 간격 (기본: 30초)
  pollInterval: "30s"
  # 로그 레벨
  logLevel: "info"
  # 동시 처리할 최대 인터페이스 수 (병렬 처리)
  # - 더 많은 인터페이스를 동시에 처리하려면 이 값을 늘리세요
  # - 시스템 리소스를 고려하여 적절한 값을 설정하세요
  maxConcurrentTasks: 5
  # 폴링 백오프 설정 (선택사항)
  # 지수 백오프(Exponential Backoff)란?
  # - 실패 시 재시도 간격을 지수적으로 증가시켜 DB/네트워크 부하를 줄이는 기법
  # - 예: 30s → 실패 → 60s → 실패 → 120s → 실패 → 240s...
  # - 성공 시 즉시 기본 간격(pollInterval)으로 복귀
  backoff:
    # 백오프 활성화 여부 (기본: true)
    # - true: 지능적 폴링 (권장)
    # - false: 고정 간격 폴링
    enabled: true
    
    # 최대 폴링 간격 (기본: pollInterval * 10)
    # 장시간 장애 시에도 이 값 이상으로는 증가하지 않음
    maxInterval: "300s"
    
    # 백오프 지수 (기본: 2.0)
    # - 2.0: 매 실패마다 간격이 2배씩 증가 (30s → 60s → 120s...)
    # - 1.5: 완만한 증가 (더 자주 재시도)
    # - 3.0: 급격한 증가 (더 적게 재시도)
    multiplier: 2.0

# 리소스 제한
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 노드 셀렉터 - K8s 클러스터에 조인된 노드만
nodeSelector: {}
  # kubernetes.io/hostname: node1

tolerations:
  # 컨트롤 플레인 노드에도 배포되도록 설정
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

affinity: {}

# 서비스 어카운트
serviceAccount:
  create: true
  name: ""

# 보안 컨텍스트
securityContext:
  privileged: true  # 네트워크 설정을 위해 필요
  capabilities:
    add:
      - NET_ADMIN
      - SYS_ADMIN