apiVersion: v1
kind: Secret
metadata:
  name: {{ include "multinic-agent.fullname" . }}-db
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.password | b64enc | quote }}