{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "multinic-agent.serviceAccountName" . }}
  labels:
    {{- include "multinic-agent.labels" . | nindent 4 }}
{{- end }}